//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mall.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Footprint
    {
        [Key]
        public int Id { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<System.DateTime> DataDelete { get; set; }
        public int Status { get; set; }
    }
}
